#!/usr/bin/env python3
from pathlib import Path
import subprocess
import sys
import xml.etree.ElementTree as ET

PINNED_COMMIT = "fc9fe0c56908846c9f1817ed3a50618ab6fb5556"

if len(sys.argv) != 2:
    raise SystemExit("usage: apply_runtime_bridge_overlay.py <pcapdroid-root>")

root = Path(sys.argv[1]).resolve()


def read(rel: str) -> str:
    return (root / rel).read_text(encoding="utf-8")


def write(rel: str, data: str) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data, encoding="utf-8")


def replace_once(rel: str, old: str, new: str) -> None:
    data = read(rel)
    count = data.count(old)
    if count != 1:
        raise RuntimeError(f"{rel}: expected exactly one match, found {count}")
    write(rel, data.replace(old, new, 1))


head = subprocess.check_output(
    ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
).strip()
if head != PINNED_COMMIT:
    raise RuntimeError(f"unexpected upstream commit: {head}")

# ---------------------------------------------------------------------------
# Runtime data bridge
# ---------------------------------------------------------------------------
# This bridge does NOT hook or read another app's memory. A target app owned by
# the user explicitly sends already-decoded/parsed data to Salin Jaringan.
# The provider verifies that the sender is one of the apps selected in the
# existing target-app filter before accepting anything.

store_java = r'''/* Generated by Salin Jaringan runtime bridge overlay. */
package com.emanuelef.remote_capture.runtime;

import android.content.Context;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Comparator;
import java.util.UUID;

public final class RuntimeDataStore {
    private static final String DIR_NAME = "runtime_data";
    private static final int MAX_RECORDS = 100;
    private static final Gson PRETTY_GSON = new GsonBuilder().setPrettyPrinting().create();

    private RuntimeDataStore() {}

    private static File getDir(Context context) {
        File dir = new File(context.getFilesDir(), DIR_NAME);
        if (!dir.exists() && !dir.mkdirs() && !dir.exists())
            throw new IllegalStateException("cannot create runtime data directory");
        return dir;
    }

    public static synchronized String save(Context context, String sourcePackage,
                                           String label, String json, String text) throws IOException {
        JsonObject root = new JsonObject();
        root.addProperty("format", "salin-jaringan/runtime-v1");
        root.addProperty("waktu_epoch_ms", System.currentTimeMillis());
        root.addProperty("aplikasi_sumber", sourcePackage);
        if (label != null && !label.isBlank())
            root.addProperty("label", label);

        String incoming = (json != null) ? json : text;
        if (incoming == null)
            incoming = "";

        if (json != null) {
            try {
                JsonElement parsed = JsonParser.parseString(json);
                root.addProperty("jenis", "json");
                root.add("data", parsed);
            } catch (JsonSyntaxException e) {
                root.addProperty("jenis", "teks");
                root.addProperty("data_teks", incoming);
                root.addProperty("catatan", "Input diberi label JSON tetapi tidak valid; disimpan sebagai teks.");
            }
        } else {
            root.addProperty("jenis", "teks");
            root.addProperty("data_teks", incoming);
        }

        String name = "runtime_" + System.currentTimeMillis() + "_" +
                UUID.randomUUID().toString().substring(0, 8) + ".json";
        File outFile = new File(getDir(context), name);
        try (OutputStreamWriter writer = new OutputStreamWriter(
                new FileOutputStream(outFile), StandardCharsets.UTF_8)) {
            PRETTY_GSON.toJson(root, writer);
        }

        trimOld(context);
        return name;
    }

    private static void trimOld(Context context) {
        File[] files = listFiles(context);
        for (int i = MAX_RECORDS; i < files.length; i++)
            //noinspection ResultOfMethodCallIgnored
            files[i].delete();
    }

    public static File[] listFiles(Context context) {
        File[] files = getDir(context).listFiles((dir, name) -> name.endsWith(".json"));
        if (files == null)
            return new File[0];
        Arrays.sort(files, Comparator.comparingLong(File::lastModified).reversed());
        return files;
    }

    private static String readFile(File file) throws IOException {
        byte[] data = new byte[(int) file.length()];
        try (FileInputStream in = new FileInputStream(file)) {
            int offset = 0;
            while (offset < data.length) {
                int n = in.read(data, offset, data.length - offset);
                if (n < 0)
                    break;
                offset += n;
            }
        }
        return new String(data, StandardCharsets.UTF_8);
    }

    public static String preview(Context context, int limit) {
        File[] files = listFiles(context);
        if (files.length == 0)
            return "";

        StringBuilder out = new StringBuilder();
        int count = Math.min(limit, files.length);
        for (int i = 0; i < count; i++) {
            try {
                if (i > 0)
                    out.append("\n\n──────────\n\n");
                out.append(readFile(files[i]));
            } catch (IOException e) {
                out.append("{\"error\":\"").append(e.getMessage()).append("\"}");
            }
        }
        return out.toString();
    }

    public static String exportAll(Context context) {
        JsonArray all = new JsonArray();
        for (File file : listFiles(context)) {
            try {
                all.add(JsonParser.parseString(readFile(file)));
            } catch (Exception e) {
                JsonObject error = new JsonObject();
                error.addProperty("file", file.getName());
                error.addProperty("error", e.getMessage());
                all.add(error);
            }
        }
        return PRETTY_GSON.toJson(all);
    }

    public static int count(Context context) {
        return listFiles(context).length;
    }

    public static void clear(Context context) {
        for (File file : listFiles(context))
            //noinspection ResultOfMethodCallIgnored
            file.delete();
    }
}
'''
write("app/src/main/java/com/emanuelef/remote_capture/runtime/RuntimeDataStore.java", store_java)

provider_java = r'''/* Generated by Salin Jaringan runtime bridge overlay. */
package com.emanuelef.remote_capture.runtime;

import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Binder;
import android.os.Bundle;
import android.os.Process;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.preference.PreferenceManager;

import com.emanuelef.remote_capture.model.Prefs;

import java.nio.charset.StandardCharsets;
import java.util.Set;

public class RuntimeDataProvider extends ContentProvider {
    public static final String AUTHORITY = "com.rmtampu.salinjaringan.runtime";
    public static final String METHOD_CAPTURE = "capture";
    private static final int MAX_BYTES = 2 * 1024 * 1024;

    @Override
    public boolean onCreate() {
        return true;
    }

    @Nullable
    private String getAuthorizedSource(Context context, int uid) {
        if (uid == Process.myUid())
            return context.getPackageName();

        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
        Set<String> targets = Prefs.getAppFilter(prefs);
        if (targets == null || targets.isEmpty())
            return null;

        PackageManager pm = context.getPackageManager();
        String[] packages = pm.getPackagesForUid(uid);
        if (packages == null)
            return null;

        for (String pkg : packages) {
            if (targets.contains(pkg))
                return pkg;
        }
        return null;
    }

    @Override
    public Bundle call(@NonNull String method, @Nullable String arg, @Nullable Bundle extras) {
        if (!METHOD_CAPTURE.equals(method))
            return super.call(method, arg, extras);

        Context context = getContext();
        if (context == null)
            throw new IllegalStateException("context unavailable");

        String source = getAuthorizedSource(context, Binder.getCallingUid());
        if (source == null)
            throw new SecurityException("Pengirim bukan aplikasi target yang dipilih.");

        if (extras == null)
            throw new IllegalArgumentException("data kosong");

        String json = extras.getString("json");
        String text = extras.getString("text");
        String label = extras.getString("label");
        if (json == null && text == null)
            throw new IllegalArgumentException("isi json atau text diperlukan");

        String payload = (json != null) ? json : text;
        if (payload.getBytes(StandardCharsets.UTF_8).length > MAX_BYTES)
            throw new IllegalArgumentException("data runtime melebihi 2 MB per kiriman");

        Bundle result = new Bundle();
        try {
            String name = RuntimeDataStore.save(context, source, label, json, text);
            result.putBoolean("ok", true);
            result.putString("file", name);
        } catch (Exception e) {
            result.putBoolean("ok", false);
            result.putString("error", e.getMessage());
        }
        return result;
    }

    @Nullable @Override public Cursor query(@NonNull Uri uri, @Nullable String[] projection,
                                             @Nullable String selection, @Nullable String[] selectionArgs,
                                             @Nullable String sortOrder) { return null; }
    @Nullable @Override public String getType(@NonNull Uri uri) { return "application/json"; }
    @Nullable @Override public Uri insert(@NonNull Uri uri, @Nullable ContentValues values) { return null; }
    @Override public int delete(@NonNull Uri uri, @Nullable String selection,
                                @Nullable String[] selectionArgs) { return 0; }
    @Override public int update(@NonNull Uri uri, @Nullable ContentValues values,
                                @Nullable String selection, @Nullable String[] selectionArgs) { return 0; }
}
'''
write("app/src/main/java/com/emanuelef/remote_capture/runtime/RuntimeDataProvider.java", provider_java)

activity_java = r'''/* Generated by Salin Jaringan runtime bridge overlay. */
package com.emanuelef.remote_capture.activities;

import android.content.Intent;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AlertDialog;

import com.emanuelef.remote_capture.R;
import com.emanuelef.remote_capture.runtime.RuntimeDataStore;

import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

public class RuntimeDataActivity extends BaseActivity {
    private TextView mStatus;
    private TextView mPreview;
    private String mPendingExport;

    private final ActivityResultLauncher<Intent> mExportLauncher =
            registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result -> {
                if (result.getResultCode() != RESULT_OK || result.getData() == null ||
                        result.getData().getData() == null || mPendingExport == null)
                    return;

                try (OutputStream out = getContentResolver().openOutputStream(
                        result.getData().getData(), "rwt")) {
                    if (out == null)
                        throw new IllegalStateException("lokasi penyimpanan tidak tersedia");
                    out.write(mPendingExport.getBytes(StandardCharsets.UTF_8));
                    Toast.makeText(this, R.string.runtime_export_ok, Toast.LENGTH_SHORT).show();
                } catch (Exception e) {
                    Toast.makeText(this, R.string.runtime_export_failed, Toast.LENGTH_LONG).show();
                } finally {
                    mPendingExport = null;
                }
            });

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle(R.string.runtime_data_title);

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(16), dp(16), dp(16), dp(16));
        root.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

        TextView info = new TextView(this);
        info.setText(R.string.runtime_data_info);
        info.setTextSize(16);
        root.addView(info, new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));

        mStatus = new TextView(this);
        LinearLayout.LayoutParams statusLp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        statusLp.topMargin = dp(14);
        root.addView(mStatus, statusLp);

        LinearLayout buttons = new LinearLayout(this);
        buttons.setOrientation(LinearLayout.HORIZONTAL);
        LinearLayout.LayoutParams buttonsLp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        buttonsLp.topMargin = dp(12);
        root.addView(buttons, buttonsLp);

        Button refresh = new Button(this);
        refresh.setText(R.string.runtime_refresh);
        refresh.setOnClickListener(v -> refresh());
        buttons.addView(refresh, new LinearLayout.LayoutParams(0,
                ViewGroup.LayoutParams.WRAP_CONTENT, 1f));

        Button export = new Button(this);
        export.setText(R.string.runtime_export);
        export.setOnClickListener(v -> exportAll());
        buttons.addView(export, new LinearLayout.LayoutParams(0,
                ViewGroup.LayoutParams.WRAP_CONTENT, 1f));

        Button clear = new Button(this);
        clear.setText(R.string.runtime_clear);
        clear.setOnClickListener(v -> confirmClear());
        LinearLayout.LayoutParams clearLp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        clearLp.topMargin = dp(8);
        root.addView(clear, clearLp);

        ScrollView scroll = new ScrollView(this);
        mPreview = new TextView(this);
        mPreview.setTextIsSelectable(true);
        mPreview.setTextSize(13);
        mPreview.setPadding(0, dp(12), 0, dp(24));
        scroll.addView(mPreview, new ScrollView.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
        root.addView(scroll, new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, 0, 1f));

        setContentView(root);
        refresh();
    }

    private void refresh() {
        int count = RuntimeDataStore.count(this);
        mStatus.setText(getString(R.string.runtime_data_status, count));
        String preview = RuntimeDataStore.preview(this, 20);
        mPreview.setText(preview.isEmpty() ? getString(R.string.runtime_data_empty) : preview);
    }

    private void exportAll() {
        if (RuntimeDataStore.count(this) == 0) {
            Toast.makeText(this, R.string.runtime_data_empty, Toast.LENGTH_SHORT).show();
            return;
        }

        mPendingExport = RuntimeDataStore.exportAll(this);
        Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("application/json");
        intent.putExtra(Intent.EXTRA_TITLE, "SalinJaringan_runtime_" +
                System.currentTimeMillis() + ".json");
        mExportLauncher.launch(intent);
    }

    private void confirmClear() {
        new AlertDialog.Builder(this)
                .setMessage(R.string.runtime_clear_confirm)
                .setPositiveButton(R.string.yes, (dialog, which) -> {
                    RuntimeDataStore.clear(this);
                    refresh();
                })
                .setNegativeButton(R.string.no, null)
                .show();
    }
}
'''
write("app/src/main/java/com/emanuelef/remote_capture/activities/RuntimeDataActivity.java", activity_java)

# Add Indonesian strings.
strings_path = root / "app/src/main/res/values/strings.xml"
strings_tree = ET.parse(strings_path)
strings_root = strings_tree.getroot()


def set_string(name: str, value: str) -> None:
    for child in strings_root.findall("string"):
        if child.attrib.get("name") == name:
            child.text = value
            return
    node = ET.SubElement(strings_root, "string", {"name": name})
    node.text = value


set_string("runtime_data_title", "Data Runtime")
set_string("runtime_data_info", "Salinan data yang sudah diproses oleh aplikasi target. Aplikasi target harus mendukung Jembatan Runtime dan harus dipilih sebagai aplikasi target di Salin Jaringan.")
set_string("runtime_data_status", "%1$d data runtime tersimpan")
set_string("runtime_data_empty", "Belum ada data runtime. Jalankan aplikasi target yang sudah mendukung Jembatan Runtime.")
set_string("runtime_refresh", "Segarkan")
set_string("runtime_export", "Simpan semua JSON")
set_string("runtime_clear", "Hapus data runtime")
set_string("runtime_clear_confirm", "Hapus semua data runtime yang tersimpan?")
set_string("runtime_export_ok", "Data runtime berhasil disimpan sebagai JSON.")
set_string("runtime_export_failed", "Gagal menyimpan data runtime.")
ET.indent(strings_tree, space="    ")
strings_tree.write(strings_path, encoding="utf-8", xml_declaration=True)

# Add the Data Runtime item to the navigation drawer.
nav_rel = "app/src/main/res/menu/nav_items.xml"
nav = read(nav_rel)
nav_anchor = '''        <item\n            android:id="@+id/item_apps"\n            android:title="@string/apps"\n            android:icon="@drawable/ic_apps" />\n'''
nav_replacement = nav_anchor + '''        <item\n            android:id="@+id/runtime_data"\n            android:title="@string/runtime_data_title"\n            android:icon="@drawable/ic_text_snippet" />\n'''
if nav.count(nav_anchor) != 1:
    raise RuntimeError("nav_items.xml: item_apps anchor not found")
write(nav_rel, nav.replace(nav_anchor, nav_replacement, 1))

# Open the runtime screen from the navigation drawer.
main_rel = "app/src/main/java/com/emanuelef/remote_capture/activities/MainActivity.java"
main = read(main_rel)
main_anchor = '''        if(id == R.id.item_apps) {\n            if(CaptureService.getConnsRegister() != null) {\n                Intent intent = new Intent(MainActivity.this, AppsActivity.class);\n                startActivity(intent);\n            } else\n                Utils.showToast(this, R.string.start_capture_first);\n        } else if(id == R.id.malware_detection) {\n'''
main_replacement = '''        if(id == R.id.item_apps) {\n            if(CaptureService.getConnsRegister() != null) {\n                Intent intent = new Intent(MainActivity.this, AppsActivity.class);\n                startActivity(intent);\n            } else\n                Utils.showToast(this, R.string.start_capture_first);\n        } else if(id == R.id.runtime_data) {\n            Intent intent = new Intent(MainActivity.this, RuntimeDataActivity.class);\n            startActivity(intent);\n        } else if(id == R.id.malware_detection) {\n'''
if main.count(main_anchor) != 1:
    raise RuntimeError("MainActivity.java: navigation anchor not found")
write(main_rel, main.replace(main_anchor, main_replacement, 1))

# Register the viewer activity and the exported bridge provider.
manifest_rel = "app/src/main/AndroidManifest.xml"
manifest = read(manifest_rel)
activity_anchor = '''        <activity\n            android:name=".activities.AppFilterActivity"\n            android:launchMode="singleTop"\n            android:parentActivityName=".activities.MainActivity" />\n\n        <service\n'''
activity_replacement = '''        <activity\n            android:name=".activities.AppFilterActivity"\n            android:launchMode="singleTop"\n            android:parentActivityName=".activities.MainActivity" />\n        <activity\n            android:name=".activities.RuntimeDataActivity"\n            android:launchMode="singleTop"\n            android:parentActivityName=".activities.MainActivity" />\n\n        <provider\n            android:name=".runtime.RuntimeDataProvider"\n            android:authorities="com.rmtampu.salinjaringan.runtime"\n            android:exported="true" />\n\n        <service\n'''
if manifest.count(activity_anchor) != 1:
    raise RuntimeError("AndroidManifest.xml: activity/service anchor not found")
write(manifest_rel, manifest.replace(activity_anchor, activity_replacement, 1))

# CI guardrails.
assert "RuntimeDataProvider" in read(manifest_rel)
assert "runtime_data" in read(nav_rel)
assert "RuntimeDataActivity.class" in read(main_rel)
assert "Prefs.getAppFilter" in read("app/src/main/java/com/emanuelef/remote_capture/runtime/RuntimeDataProvider.java")
assert "MAX_BYTES = 2 * 1024 * 1024" in read("app/src/main/java/com/emanuelef/remote_capture/runtime/RuntimeDataProvider.java")
assert "MAX_RECORDS = 100" in read("app/src/main/java/com/emanuelef/remote_capture/runtime/RuntimeDataStore.java")

print("Runtime bridge overlay applied")
